apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rundeck-data-pvc
  namespace: rundeck
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: oci-bv # oracle cloud class name

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-pvc
  namespace: rundeck
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: oci-bv # oracle cloud class name