apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: your_metadata_name
  namespace: rundeck
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: your_config
  data:

  - secretKey: POSTGRES_DB
    remoteRef:
      key: your_config
      property: POSTGRES_DB

  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: your_config
      property: POSTGRES_PASSWORD

  - secretKey: POSTGRES_USER
    remoteRef:
      key: your_config
      property: POSTGRES_USER
