apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-external-secret-rundeckbd
  namespace: rundeck
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: rundeck-database-secret
  data:
  - secretKey: user
    remoteRef: 
      key: rundeckdb-secrets
      property: user

  - secretKey: password
    remoteRef: 
      key: rundeckdb-secrets
      property: password

  - secretKey: database
    remoteRef: 
      key: rundeckdb-secrets
      property: database

  - secretKey: host
    remoteRef: 
      key: rundeckdb-secrets
      property: host

  - secretKey: jdbc
    remoteRef: 
      key: rundeckdb-secrets
      property: jdbc

  - secretKey: port
    remoteRef: 
      key: rundeckdb-secrets
      property: port

  - secretKey: type
    remoteRef: 
      key: rundeckdb-secrets
      property: type

  # - secretKey: 
  #   remoteRef: 
  #     key: rundeckdb-secrets
  #     property: 
