apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-external-secret-rundeck
  namespace: rundeck
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: user-credentials-secret
  data:
  - secretKey: userCredentials
    remoteRef: 
      key: rundeck-secrets
      property: userCredentials